<?php
require_once __DIR__ . "/includes/db.php";
include("../includes/admin_header.php");

$totalEvents = $conn->query("SELECT * FROM events")->num_rows;
$totalUsers = $conn->query("SELECT * FROM users WHERE role='user'")->num_rows;
$totalBookings = $conn->query("SELECT * FROM bookings")->num_rows;
$totalNotifications = $conn->query("SELECT * FROM notifications")->num_rows;
?>

<section class="hero" style="min-height:40vh;">
    <div class="hero-content reveal">
        <h2>Administrator Control Center</h2>
        <p>Manage platform activities, events, users and engagement analytics.</p>
    </div>
</section>

<h2 class="section-title">System Analytics Overview</h2>

<section class="stats-section">
    <div class="stat-box reveal"><h2><?php echo $totalEvents; ?></h2><p>Total Events</p></div>
    <div class="stat-box reveal"><h2><?php echo $totalUsers; ?></h2><p>Registered Users</p></div>
    <div class="stat-box reveal"><h2><?php echo $totalBookings; ?></h2><p>Total Bookings</p></div>
    <div class="stat-box reveal"><h2><?php echo $totalNotifications; ?></h2><p>Notifications</p></div>
</section>

<h2 class="section-title">Quick Administrative Actions</h2>

<section class="features">
    <div class="feature-box reveal">
        <h3>➕ Publish New Event</h3>
        <p>Add and schedule fresh activities instantly.</p>
        <br><a href="add_event.php" class="btn">Add Event</a>
    </div>

    <div class="feature-box reveal">
        <h3>🛠 Manage Existing Events</h3>
        <p>Edit or delete all current event listings.</p>
        <br><a href="manage_events.php" class="btn">Manage Events</a>
    </div>

    <div class="feature-box reveal">
        <h3>🔔 Notification Monitor</h3>
        <p>Track automatic user alerts generated by the system.</p>
        <br><a href="../notifications.php" class="btn">View Notifications</a>
    </div>
</section>

<?php include("../includes/admin_footer.php"); ?>